### PR TITLE
Improve performance of clock.stop method

### LINKED ISSUE #1: Handover to R is slow
Hi,

let me say that I love RcppClock and I use it frequently.
However, recently I discovered performance issues and it turned out that RcppClock itself caused those issues. Considers this simple .cpp file:
```

// [[Rcpp::depends(RcppArmadillo)]]
// [[Rcpp::depends(RcppProgress)]]
// [[Rcpp::depends(RcppClock)]]
// [[Rcpp::plugins("cpp11")]]

#include <RcppArmadillo.h>
#include <progress.hpp>
#include <RcppClock.h>
#include <thread>

// [[Rcpp::export]]
int test()
{

    int X = 50;
    int Y = 50;
    int Z = 50;

    Progress prog(X * Y * Z);
    Rcpp::Clock clock;
    arma::wall_clock timer;

    for (unsigned int x = 0; x < X; x++)
    {
        for (unsigned int y = 0; y < Y; y++)
        {
            for (unsigned int z = 0; z < Z; z++)
            {
                clock.tick("Z action");
                arma::vec tmp(100, arma::fill::randu);
                clock.tock("Z action");
                prog.increment();
            }
        }
    }

    timer.tic();
    clock.stop("times");
    double n = timer.toc();
    arma::cout << "number of seconds: " << n << arma::endl;

    return 0;
}
```

RcppArmadillo, RcppClock, and RcppProgress are needed. Then this can be easily sourced using `Rcpp::sourceCpp("test.cpp")`

Now consider the following R code:
```
[R] test()                                                                           
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
number of seconds: 86.5003
[1] 0
```

The progressbar fills up extremely quick. However, it takes 86 seconds for `clock.stop("times");` to finish. How is that?
We can see that `times`'s footprint is not tiny indeed:
```
[R] sz <- object.size(times)                                                         

[R] print(sz, units = "MB")                                                          
1.9 Mb
```

However, 86 Seconds seems a bit hefty even if we have 1.2MB of data which has to be processed in some way.

Thank you so much.
BerriJ

### PR DESCRIPTION
**Pull request by BerriJ**
Fixes https://github.com/zdebruine/RcppClock/issues/1

This is still work in Progress. Some things left to do:

- [ ] Benchmarking old vs. new implementation
- [ ] Check if results are equivalent
- [ ] Evaluate which #includes we really need (some of them were only needed for development)

You can install easily using: `devtools::install_github("zdebruine/RcppClock#2")`

### CODE REVIEW

**Comment by zdebruine** [comment]
Oh wow, we were working on this in parallel.  I've got to go, it's just about Thanksgiving here and I'll maybe take a look at this over holiday, but do compare the current dev version performance with your implementation and we'll talk about a merge if you can beat what I just pushed.

**Comment by BerriJ** [comment]
I'll have a look! At the very least it was pretty fun coding down this problem :)

I made up the following (simplified) test.cpp:
```
#include <RcppClock.h>
// #include <RcppClock_BerriJ.h>
// #include <RcppClock_zdebruine.h>
#include <thread>

// [[Rcpp::export]]
void test()
{
    int X = 20;
    int Y = 20;
    int Z = 20;

    Rcpp::Clock clock;

    for (unsigned int x = 0; x < X; x++)
    {
        for (unsigned int y = 0; y < Y; y++)
        {
            for (unsigned int z = 0; z < Z; z++)
            {
                clock.tick("Z action");
                double x;
                x = std::rand();
                clock.tock("Z action");
            }
        }
    }

    clock.stop("times");
}
```

And copied my .h file as `RcppClock_BerriJ.h` and yours as `RcppClock_zdebruine.h`, Then we can execute this in R:

Using the old `RcppClock.h` we get:
```
[R] system.time(test())
 user  system elapsed 
 72.638   0.010  72.722
```

With my proposed version we get:
```
[R] microbenchmark::microbenchmark(test(), times = 10, unit = "milliseconds")
Unit: milliseconds
   expr      min       lq     mean   median       uq      max neval
 test() 18.60965 18.77204 19.22539 19.27625 19.51202 19.97789    10
```

So its `72638/19.225 = 3778.309` times faster then the old implementation. However, If I uncomment your new file R crashes at runtime (when trying to run `test()`).

Small Update: I still cannot get your new version to work. (I'm on Ubuntu). I get the following error:
```
 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call(`_profoc_test`)
 2: test()
```

That said, I still have an Idea how to improve my Idea even further (by directly saving ticks and stocks to an ordered map).

**Comment by zdebruine** [comment]
> That said, I still have an Idea how to improve my Idea even further (by directly saving ticks and stocks to an ordered map).

Right on, so I did that :)  It wasn't necessary to actually use a `map`, something equivalent could be accomplished with fewer temporaries using pairs of vectors.

Check out the latest implementation on the `main` branch.  I moved all the duration calculations to the `tock()` function, and it's really fast.  This is probably the most efficient approach.  Using your example, I ran `microbenchmark` for your implementation and my new one:

```
Unit: milliseconds
            expr    min     lq     mean  median     uq     max neval
 test_original() 1.4573 1.5123 1.829087 1.67535 1.9657  3.2632   100
   test_BerriJ() 6.9373 7.6788 8.376485 8.27730 8.6289 10.9145   100
```

It's marginally faster.  Here's hoping it also works on your system?

**Comment by BerriJ** [comment]
This looks good. And I can also run this on my machine, well kind of.

Inside of your repository, It works, but inside of my larger project, it does not. However, this may likely be caused by my specific setup. I would propose that you make a release and then I'll report if there are still problems?
In that case I would close this PR now...

**Comment by zdebruine** [comment]
> This looks good. And I can also run this on my machine, well kind of.
> 
> Inside of your repository, It works, but inside of my larger project, it does not. However, this may likely be caused by my specific setup. I would propose that you make a release and then I'll report if there are still problems? In that case I would close this PR now...

I'm curious what about your larger project is causing the program to fail?  You can just `devtools::install_github("zdebruine/RcppClock")` to test the new release.  I'm not going to push it to CRAN until more testing.  If your current issues are unrelated to the package, you can close this PR and linked issue.  Otherwise, we should resolve it.

**Comment by BerriJ** [comment]
I "solved" the problem. It seems related to the fact that most of my development happens inside of a Docker container. I think the details do not matter much for you but the fact is: when I pre-install RcppClock inside the container, everything works as expected. And it's blazing fast! Thank you very much for your dedication to squeeze out the last bits of performance! :)
The automatic checks of my package always use the latest CRAN version of RcppClock and they run on MacOS. So when the update hits CRAN, I can report back to you if the MacOS Problem is solved.

**Comment by zdebruine** [comment]
Great, thanks for your effort on this as well.  Much appreciated.  I wouldn’t have done it without your interest and ideas.  I’ll run a CRAN check shortly and write a few more tests.  If all passes I’ll submit to CRAN soon.

**Pull request closed without merging**
